(princ "\nLoading MP-DXF ")
(princ ".")
(defun MP:DXF->load ()
  (princ "")
)
(princ ".")
(defun MP:DXF->getValueByNumber (n d)
  (cdr (assoc n d))
)
(defun MP:DXF->getEntity(d)
  (cdr (assoc 0 d))
)
(defun MP:DXF->getInsert(d)
  (cdr (assoc 10 d))
)
(defun MP:DXF->getLayer(d)
  (cdr (assoc 8 d))
)
(defun MP:DXF->getColor(d)
  (cdr (assoc 62 d))
)
(princ " [Done]")

